### ISSUE TITLE
Small 100 not working anymore. 

### ISSUE THREAD

**Issue by twicer-is-coder** [ikergarcia1996/Easy-Translate#13]
I was previously using this from sample and its no longer works now after updates.
python3 translate.py \ --sentences_path sample_text/en.txt \ --output_path sample_text/en2es.translation.small100.txt \ --source_lang en \ --target_lang es \ --model_name alirezamsh/small100

This is the log:
2023-12-06T12:38:42.665144096Z Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
2023-12-06T12:38:43.268330478Z The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
2023-12-06T12:38:43.268375418Z The tokenizer class you load from this checkpoint is 'M2M100Tokenizer'. 
2023-12-06T12:38:43.268383058Z The class this function is called from is 'SMALL100Tokenizer'.
2023-12-06T12:38:43.269837017Z Loading model from alirezamsh/small100
2023-12-06T12:38:43.269851767Z Loading custom small100 tokenizer for utils.tokenization_small100
2023-12-06T12:38:43.270022978Z Traceback (most recent call last):
2023-12-06T12:38:43.270132589Z   File "//Easy-Translate/translate.py", line 538, in <module>
2023-12-06T12:38:43.270510501Z     main(
2023-12-06T12:38:43.270625462Z   File "//Easy-Translate/translate.py", line 134, in main
2023-12-06T12:38:43.270820843Z     model, tokenizer = load_model_for_inference(
2023-12-06T12:38:43.270937283Z   File "/Easy-Translate/model.py", line 90, in load_model_for_inference
2023-12-06T12:38:43.271180565Z     tokenizer: PreTrainedTokenizerBase = AutoTokenizer.from_pretrained(
2023-12-06T12:38:43.271340276Z   File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 2045, in from_pretrained
2023-12-06T12:38:43.271888289Z     return cls._from_pretrained(
2023-12-06T12:38:43.271961479Z   File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 2256, in _from_pretrained
2023-12-06T12:38:43.272524103Z     tokenizer = cls(*init_inputs, **init_kwargs)
2023-12-06T12:38:43.272535813Z   File "/Easy-Translate/utils/tokenization_small100.py", line 153, in __init__
2023-12-06T12:38:43.272685754Z     super().__init__(
2023-12-06T12:38:43.272714444Z   File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils.py", line 366, in __init__
2023-12-06T12:38:43.272931705Z     self._add_tokens(self.all_special_tokens_extended, special_tokens=True)
2023-12-06T12:38:43.272935405Z   File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils.py", line 462, in _add_tokens
2023-12-06T12:38:43.273221467Z     current_vocab = self.get_vocab().copy()
2023-12-06T12:38:43.273318857Z   File "/Easy-Translate/utils/tokenization_small100.py", line 289, in get_vocab
2023-12-06T12:38:43.273603199Z     vocab = {self.convert_ids_to_tokens(i): i for i in range(self.vocab_size)}
2023-12-06T12:38:43.273645449Z   File "/Easy-Translate/utils/tokenization_small100.py", line 192, in vocab_size
2023-12-06T12:38:43.273817970Z     return len(self.encoder) + len(self.lang_token_to_id) + self.num_madeup_words
2023-12-06T12:38:43.274002501Z AttributeError: 'SMALL100Tokenizer' object has no attribute 'encoder'. Did you mean: 'encode'?

This model own space has same error:
https://huggingface.co/spaces/alirezamsh/small100

**Comment by ikergarcia1996** [comment]
Hi @twicer-is-coder 
Small100 is incompatible with transformers versions 4.34 and above. Until the author updates the custom tokenizer, you will need to downgrade transformers to an earlier version if you want to use this model.
